package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;
import static org.assertj.core.api.Assertions.*;
import org.junit.jupiter.api.Test;
import java.time.*;import java.util.*;
class CandidateContractTest {
 final Instant start=Instant.parse("2026-09-12T13:00:00Z"),end=start.plusSeconds(60);
 final Request request=new Request("tracepilot-business","demo",start,end,"test");
 Evidence overview(String version){return new Evidence("o","overview","AVAILABLE",start.toString(),end.toString(),Map.of(),tree(Map.of("time",start.toString(),"deploymentVersion",version,"pool",Map.of("active",0,"idle",8))));}
 com.fasterxml.jackson.databind.node.ObjectNode report(String scope){return (com.fasterxml.jackson.databind.node.ObjectNode)tree(Map.of("summary","观察到采样时空闲；持续性未知","facts",List.of(),"conflicts",List.of(),"gaps",List.of("缺少时间序列"),"actions",List.of("补充采样"),"candidates",List.of(Map.of("cause","当前工作量可能低","inference",true,"confidence","UNVERIFIED","evidenceIds",List.of("o"),"mechanism","瞬时工作量低可使连接空闲","support","只在该时刻观察到空闲","contradictions","未获得反证，不等于排除其他机制","toVerify",List.of("实际工作量和后续采样"),"scope",scope))));}
 @Test void oneCandidateAndEmptyAreLegalWithoutQuota(){var r=report("SNAPSHOT_HYPOTHESIS");assertThat(CandidateContract.issues(r,List.of(overview(MetricFacts.BUSINESS_VERSION)),request)).isEmpty();r.putArray("candidates");assertThat(CandidateContract.issues(r,List.of(),request)).isEmpty();}
 @Test void unsupportedSecondHasSpecificFeedbackAndExplicitWithdrawalWorks(){var r=report("SNAPSHOT_HYPOTHESIS");var second=r.at("/candidates/0").deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)second).putArray("evidenceIds").add("missing");((com.fasterxml.jackson.databind.node.ArrayNode)r.path("candidates")).add(second);var issues=CandidateContract.issues(r,List.of(overview(MetricFacts.BUSINESS_VERSION)),request);assertThat(issues).anySatisfy(x->{assertThat(x.get("path")).isEqualTo("/candidates/1/evidenceIds");assertThat(x.get("resolution").toString()).contains("Withdraw");});assertThat(r.path("candidates")).hasSize(2);var corrected=r.deepCopy();((com.fasterxml.jackson.databind.node.ArrayNode)corrected.path("candidates")).remove(1);assertThat(CandidateContract.issues(corrected,List.of(overview(MetricFacts.BUSINESS_VERSION)),request)).isEmpty();assertThat(CandidateContract.issues(r,List.of(overview(MetricFacts.BUSINESS_VERSION)),request)).isNotEmpty();}
 @Test void overviewContentAndWindowMatterNotItsName(){assertThat(EvidenceRegistry.eventEvidence(overview(MetricFacts.BUSINESS_VERSION),request)).isTrue();assertThat(EvidenceRegistry.eventEvidence(overview("unknown"),request)).isFalse();assertThat(EvidenceRegistry.eventEvidence(overview(MetricFacts.BUSINESS_VERSION),new Request(request.service(),request.environment(),end,end.plusSeconds(20),"test"))).isFalse();}
 @Test void instantCannotPassAsEventOrSustainedObservation(){var es=List.of(overview(MetricFacts.BUSINESS_VERSION));assertThat(CandidateContract.issues(report("EVENT_HYPOTHESIS"),es,request)).anySatisfy(x->assertThat(x.get("code")).isEqualTo("SNAPSHOT_ONLY"));assertThat(CandidateContract.issues(report("TEMPORAL_HYPOTHESIS"),es,request)).anySatisfy(x->assertThat(x.get("code")).isEqualTo("MISSING_TEMPORAL_SUPPORT"));}
 @Test void twoTimesMeetStructuralTemporalFloorNotCausalProof(){var e=new Evidence("o","metrics","AVAILABLE",start.toString(),end.toString(),Map.of(),tree(Map.of("data",List.of(Map.of("time",start.toString(),"pool",Map.of("pending",2)),Map.of("time",end.toString(),"pool",Map.of("pending",4))))));assertThat(CandidateContract.issues(report("TEMPORAL_HYPOTHESIS"),List.of(e),request)).isEmpty();}
 @Test void actualFailureNeedsExplicitAssessmentNotJustAWindowLog()throws Exception{var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-real-v82.json"));var es=new ArrayList<Evidence>();for(var n:f.path("evidence"))es.add(JSON.treeToValue(n,Evidence.class));var req=JSON.treeToValue(f.path("input"),Request.class);for(var draft:f.path("drafts")){assertThat(CandidateContract.issues(draft,es,req)).anySatisfy(x->assertThat(x.get("path")).isEqualTo("/candidates/0/support"));assertThat(draft.path("candidates")).hasSize(2);}}
}
