package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.JsonNode;import java.util.*;import org.junit.jupiter.api.Test;
class CausalSufficiencyTest {
 JsonNode fixture(String name)throws Exception{return JSON.readTree(getClass().getResourceAsStream("/model/"+name+".json"));}
 List<Evidence> evidence(JsonNode f)throws Exception{var es=new ArrayList<Evidence>();for(var e:f.path("evidence"))es.add(JSON.treeToValue(e,Evidence.class));return es;}
 Request request(JsonNode f)throws Exception{return JSON.treeToValue(f.path("input"),Request.class);}
 JsonNode plan(String premise,String outcome,String note){return tree(Map.of("hypotheses",List.of(Map.of("relation","MAY_EXPLAIN","premiseFactIds",List.of(premise),"outcomeFactIds",List.of(outcome),"contradictionFactIds",List.of(),"checks",List.of("CHECK_ALTERNATIVES"),"reviewNote",note)),"checks",List.of()));}
 @Test void actualH1AndSynonymousNotesCannotExplainTheSameObservations()throws Exception{var f=fixture("causal-symptom-v86");for(String note:List.of("未完成事件造成积压","事件尚未处理，所以仍在等待","queue backlog explains delayed completion")){var p=f.path("plan").deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)p.at("/hypotheses/0")).put("reviewNote",note);var c=ReportPlan.compile(p,evidence(f),request(f),false);assertThat(c.errors()).anyMatch(x->x.startsWith("CAUSAL_SELF_REFERENCE:"));assertThat(c.report()).isEmpty();assertThat(p.path("hypotheses")).hasSize(1);}}
 @Test void aliasesOfSameSourceEventAcrossPagesAreNotIndependentMechanisms()throws Exception{var f=fixture("causal-direct-mechanism");var e=evidence(f).getFirst();var duplicate=new Evidence("duplicate-page",e.source(),e.status(),e.start(),e.end(),e.locator(),e.data());var p=plan(FactReferences.id(e.id(),"/data/1/errorType"),FactReferences.id(duplicate.id(),"/data/1/errorType"),"synonym");assertThat(ReportPlan.compile(p,List.of(e,duplicate),request(f),false).errors()).anyMatch(x->x.startsWith("CAUSAL_SELF_REFERENCE"));}
 @Test void realDirectMechanismCanPassWithoutRequiringDeepestCause()throws Exception{var f=fixture("causal-direct-mechanism");var e=evidence(f).getFirst();assertThat(e.data().at("/data/1/errorType").asText()).isEqualTo("CannotGetJdbcConnectionException");assertThat(e.data().at("/data/1/message").asText()).isEqualTo("authentication_store_unavailable");var c=ReportPlan.compile(plan(FactReferences.id(e.id(),"/data/1/errorType"),FactReferences.id(e.id(),"/data/1/message"),"Connection acquisition failure prevents the authentication store query; deeper cause not established."),List.of(e),request(f),false);assertThat(c.errors()).isEmpty();assertThat(c.report().path("candidates")).hasSize(1);assertThat(c.report().at("/causalAssessment/humanReview").asText()).isEqualTo("PENDING");}
 @Test void scopeDoesNotProveUnsupportedDeepClaimInUnreviewedNote()throws Exception{var f=fixture("causal-direct-mechanism");var e=evidence(f).getFirst();var c=ReportPlan.compile(plan(FactReferences.id(e.id(),"/data/1/errorType"),FactReferences.id(e.id(),"/data/1/message"),"A connection leak is the confirmed deepest root cause."),List.of(e),request(f),false);assertThat(c.errors()).isEmpty();assertThat(c.report().at("/reviewNotes/0/status").asText()).isEqualTo("UNREVIEWED_NOT_REPORT_FACT");assertThat(c.report().path("candidates").toString()).doesNotContain("connection leak");assertThat(c.report().at("/causalAssessment/doesNotEstablishCausality").asBoolean()).isTrue();}
 @Test void ambiguousEvidenceCanExplicitlyEndUndeterminedWithoutSilentDraftRepair()throws Exception{var f=fixture("causal-symptom-v86");var explicitWithdrawal=tree(Map.of("hypotheses",List.of(),"checks",List.of("COLLECT_LOGS","COLLECT_METRICS","INSPECT_STATE")));var c=ReportPlan.compile(explicitWithdrawal,evidence(f),request(f),false);assertThat(c.errors()).isEmpty();assertThat(c.report().path("summary").asText()).contains("已确认下列观测事实","根因未确定","其他症状");assertThat(c.report().path("facts")).isNotEmpty();assertThat(c.report().path("candidates")).isEmpty();assertThat(ReportPlan.compile(f.path("plan"),evidence(f),request(f),false).errors()).isNotEmpty();}
 @Test void wrongAbstentionCannotBeMarkedAutomaticCausalSuccess()throws Exception{var f=fixture("causal-direct-mechanism");var c=ReportPlan.compile(tree(Map.of("hypotheses",List.of(),"checks",List.of())),evidence(f),request(f),false);assertThat(c.errors()).isEmpty();assertThat(c.report().at("/causalAssessment/status").asText()).isEqualTo("UNDETERMINED");assertThat(c.report().at("/causalAssessment/structuralChecksOnly").asBoolean()).isTrue();assertThat(c.report().at("/causalAssessment/humanReview").asText()).isEqualTo("PENDING"); /* Assisted audit must flag this false abstention; this is not a model quality test. */}
 @Test void pendingAndOldestDefinitionsDoNotPretendToMeasureQueueWait()throws Exception{var f=fixture("causal-symptom-v86");var facts=MetricFacts.generate(evidence(f),request(f));assertThat(encode(facts)).contains("status <> DONE","including PENDING/PROCESSING/FAILED","not measured queue-wait or lease duration");}
 @Test void addingObservedOutcomeDoesNotEraseAnIndependentMechanismPremise()throws Exception{
  var f=fixture("causal-direct-mechanism");var es=evidence(f);var e=es.getFirst();String cause=FactReferences.id(e.id(),"/data/1/errorType"),symptom=FactReferences.id(e.id(),"/data/1/message");
  var p=plan(cause,symptom,"Offline counterexample, not a signed model answer.");
  ((com.fasterxml.jackson.databind.node.ObjectNode)p.at("/hypotheses/0")).set("premiseFactIds",tree(List.of(cause,symptom)));
  var result=ReportPlan.compile(p,es,request(f),false);assertThat(result.errors()).isEmpty();assertThat(result.report().at("/causalAssessment/humanReview").asText()).isEqualTo("PENDING");
  assertThat(result.report().at("/modelPlan/hypotheses/0/premiseFactIds")).isEqualTo(tree(List.of(cause,symptom)));
 }
}
