package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class EventTimelineTest {
 JsonNode fixture()throws Exception{return parse(new String(getClass().getResourceAsStream("/model/timeline-v882.json").readAllBytes(),java.nio.charset.StandardCharsets.UTF_8));}
 List<Evidence> evidence()throws Exception{var out=new ArrayList<Evidence>();for(var e:fixture().path("evidence"))out.add(JSON.treeToValue(e,Evidence.class));return out;}
 Request request(){return new Request("tracepilot-business","demo",Instant.parse("2026-09-15T05:54:07.715529Z"),Instant.parse("2026-09-15T05:55:02.161192Z"),"通知延迟");}
 JsonNode node(EventTimeline.Catalog c,String action,String time){return c.nodes().stream().filter(n->n.path("action").asText().equals(action)&&n.path("eventTime").asText().equals(time)).findFirst().orElseThrow();}
 @Test void actualAttemptsAreNotRenamedAsFirstOrCommit()throws Exception{var c=EventTimeline.build(evidence(),request());assertThat(c.nodes()).hasSize(12);
  var start=node(c,"notification_write_started","2026-09-15T05:54:09.334Z");var retry=node(c,"notification_write_started","2026-09-15T05:55:01.868Z");assertThat(start.path("observedAttemptOrdinal").asText()).isEqualTo("1");assertThat(retry.path("observedAttemptOrdinal").asText()).isEqualTo("2");assertThat(start.path("attemptId")).isNotEqualTo(retry.path("attemptId"));
  assertThat(EventTimeline.display(retry)).contains("不表示写入成功或提交","非生命周期首次");assertThat(EventTimeline.display(node(c,"notification_write_committed","2026-09-15T05:55:01.874Z"))).contains("提交后观测（非精确提交时刻）");assertThat(c.gaps().toString()).contains("创建时刻","未知");
 }
 @Test void missingFirstAttemptNeverInventsOperation()throws Exception{var es=evidence();var e=es.get(1);var data=e.data().deepCopy();var rows=JSON.createArrayNode();for(var row:data.path("data"))if(!row.path("attemptId").asText().equals("1ef2048c-0e15-44cd-9355-90a1f36ae212"))rows.add(row);((ObjectNode)data).set("data",rows);var c=EventTimeline.build(List.of(copy(e,data)),request());assertThat(c.nodes().toString()).doesNotContain("05:54:09.334");assertThat(c.gaps().toString()).contains("生命周期首次尝试","未知");assertThat(c.nodes().stream().filter(n->n.path("action").asText().equals("notification_write_started")).findFirst().orElseThrow().path("observedAttemptOrdinal").asText()).isEqualTo("1");}
 @Test void shuffledDuplicatesAndParallelEventsKeepIdentity()throws Exception{var e=evidence().get(1);var data=e.data().deepCopy();var rows=JSON.createArrayNode();var originals=new ArrayList<JsonNode>();e.data().path("data").forEach(originals::add);Collections.shuffle(originals,new Random(4));originals.forEach(rows::add);originals.forEach(rows::add);for(var row:originals){var other=(ObjectNode)row.deepCopy();other.put("eventId","OTHER");other.put("evidenceId","other-"+row.path("evidenceId").asText());rows.add(other);}((ObjectNode)data).set("data",rows);var c=EventTimeline.build(List.of(copy(e,data)),request());assertThat(c.nodes()).hasSize(24);for(var n:c.nodes())for(var source:n.path("sources"))assertThat(data.at(source.path("pointer").asText()).path("eventId").asText()).isEqualTo(n.path("eventId").asText());}
 @Test void failedWriteCannotProduceSuccessNode()throws Exception{var e=evidence().get(1);var data=e.data().deepCopy();var rows=JSON.createArrayNode();for(var row:data.path("data"))if(row.path("attemptId").asText().equals("1ef2048c-0e15-44cd-9355-90a1f36ae212"))rows.add(row);((ObjectNode)data).set("data",rows);var c=EventTimeline.build(List.of(copy(e,data)),request());assertThat(c.nodes().toString()).doesNotContain("notification_write_committed","event_delivery_completed");assertThat(c.gaps().toString()).contains("未观测 notification_write_committed");}
 @Test void equalClockAndOtherInstanceAreUncertain()throws Exception{var e=evidence().get(1);var data=e.data().deepCopy();((ObjectNode)data.path("data").get(0)).put("instanceId","other");var c=EventTimeline.build(List.of(copy(e,data)),request());assertThat(c.nodes()).allMatch(n->n.path("observedAttemptOrdinal").asText().equals("UNKNOWN"));}
 @Test void collectionTimeCannotMoveEventIntoIncident()throws Exception{var e=evidence().get(1);var data=e.data().deepCopy();for(var row:data.path("data"))((ObjectNode)row).put("time","2026-09-15T04:00:00Z");assertThat(EventTimeline.build(List.of(copy(e,data)),request()).nodes()).isEmpty();}
 @Test void actualWrongReviewProseRejectedAndCorrectedNodeRelationsRender()throws Exception{var es=evidence();var plan=fixture().path("report").path("modelPlan");assertThat(plan.path("hypotheses")).isNotEmpty();var bad=ReportPlan.compile(plan,es,request(),false);assertThat(bad.errors().toString()).contains("TIMELINE_PROSE_NOT_ALLOWED","TIMELINE_REFERENCE_MISMATCH");
  var corrected=plan.deepCopy();for(var h:corrected.path("hypotheses"))adaptPlan((ObjectNode)h,es,request());var result=ReportPlan.compile(corrected,es,request(),false);assertThat(result.errors()).isEmpty();assertThat(result.report().path("reviewNotes")).isEmpty();
  var c=EventTimeline.build(es,request());for(var fact:result.report().path("facts")){var n=c.forFact(fact);if(n!=null)assertThat(fact.path("text").asText()).contains(n.path("eventTime").asText(),EventTimeline.ACTIONS.get(n.path("action").asText()));}
  // H3's causal relation remains a human question. Structural correction never proves it true.
  assertThat(result.report().path("causalAssessment").path("humanReview").asText()).isEqualTo("PENDING");
 }
 @Test void unknownAndWrongNodeIdsRejected()throws Exception{var es=evidence();var plan=fixture().path("report").path("modelPlan").deepCopy();for(var h:plan.path("hypotheses"))adaptPlan((ObjectNode)h,es,request());((ObjectNode)plan.path("hypotheses").get(0)).set("timelineNodeIds",tree(List.of("Tunknown")));var bad=ReportPlan.compile(plan,es,request(),false);assertThat(bad.errors().toString()).contains("UNKNOWN_OR_UNAUTHORIZED_TIMELINE_NODE","TIMELINE_REFERENCE_MISMATCH");}
 @Test void emptyEvidenceAndHistoricalReportsRemainReadable()throws Exception{var c=ReportPlan.compile(tree(Map.of("hypotheses",List.of(),"checks",List.of())),List.of(),request(),true);assertThat(c.errors()).isEmpty();assertThat(c.report().path("candidates")).isEmpty();var old=fixture().path("report");assertThat(parse(encode(old))).isEqualTo(old);assertThat(old.path("schemaVersion").asText()).isEqualTo("reviewed-report-v4");}
 static Evidence copy(Evidence e,JsonNode data){return new Evidence(e.id(),e.source(),e.status(),e.start(),e.end(),e.locator(),data);}
 // Test provider's explicit new-contract response, never runtime normalization of illegal IDs.
 static void adaptPlan(ObjectNode plan,List<Evidence> es,Request r){var c=EventTimeline.build(es,r);var facts=new HashMap<String,JsonNode>();FactReferences.catalog(es,r).forEach(f->facts.put(tree(f).path("factId").asText(),tree(f)));var ids=new LinkedHashSet<String>();for(String k:List.of("premiseFactIds","outcomeFactIds","contradictionFactIds"))for(var ref:plan.path(k)){var f=facts.get(ref.asText());if(f!=null){var n=c.forFact(f);if(n!=null)ids.add(n.path("nodeId").asText());}}if(!ids.isEmpty()){plan.remove("reviewNote");plan.set("timelineNodeIds",tree(ids));}}
 static void adaptReview(JsonNode review,List<Evidence> es,Request r){for(var a:review.path("assessments"))if(a.path("plan").isObject())adaptPlan((ObjectNode)a.path("plan"),es,r);}
}
