package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.JsonNode;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class EvidencePurposeTest {
 final Request r=new Request("tracepilot-business","demo",Instant.parse("2026-09-12T15:00:00Z"),Instant.parse("2026-09-12T15:01:00Z"),"fixture");
 Evidence sample(String id,String time,String collected){return new Evidence(id,"overview","AVAILABLE",time,time,Map.of(),tree(Map.of("time",time,"collectedAt",collected,"deploymentVersion",MetricFacts.BUSINESS_VERSION,"instanceId","instance-A","events",Map.of("pending",8,"success",24),"http",Map.of("intervalCount",5))));}
 JsonNode fact(Evidence e,String pointer){return tree(FactReferences.catalog(List.of(e),r).stream().filter(v->tree(v).path("pointer").asText().equals(pointer)).findFirst().orElseThrow());}
 JsonNode plan(String id){return tree(Map.of("relation","MAY_EXPLAIN","premiseFactIds",List.of(id),"outcomeFactIds",List.of(),"contradictionFactIds",List.of(),"checks",List.of("VERIFY_MECHANISM")));}
 JsonNode seed(){return tree(Hypotheses.seed(tree(List.of(Map.of("hypothesis","待验证", "evidenceIds",List.of("old"))))));}
 JsonNode assessment(String status,JsonNode plan){return tree(Map.of("assessments",List.of(Map.of("hypothesisId","H1","status",status,"plan",plan,"gaps",List.of("人工核对机制")))));}
 @Test void delayedCollectionDoesNotExcludeActualWindowObservation(){var e=sample("a",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());var use=EvidenceUse.classify(fact(e,"/events/pending"),e,r);assertThat(use.get("causeEligible")).isEqualTo(true);assertThat(use.get("eventTime")).isEqualTo(r.start().plusSeconds(20).toString());assertThat(use.get("collectedAt")).isEqualTo(r.end().plusSeconds(10).toString());}
 @Test void cumulativeAndIntervalWithoutRecordedStartCannotBecomeWindowCounts(){var e=sample("a",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());assertThat(EvidenceUse.classify(fact(e,"/events/success"),e,r).get("purpose")).isEqualTo("BACKGROUND");assertThat(EvidenceUse.classify(fact(e,"/http/intervalCount"),e,r).get("purpose")).isEqualTo("COVERAGE_UNKNOWN");}
 @Test void pageRetrievedAfterWindowUsesRowTimesNotReceiptOrEnvelope(){var a=sample("a",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());var e=new Evidence("page","metrics","AVAILABLE",r.end().plusSeconds(10).toString(),r.end().plusSeconds(10).toString(),Map.of(),tree(Map.of("data",List.of(a.data()))));assertThat(EvidenceUse.classify(fact(e,"/data/0/events/pending"),e,r).get("purpose")).isEqualTo("WINDOW_OBSERVATION");}
 @Test void baselineNeedsMatchingWindowObservationAndInstance(){var b=sample("b",r.start().minusSeconds(60).toString(),r.start().minusSeconds(59).toString());var i=sample("i",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());var bf=fact(b,"/events/pending");var inf=fact(i,"/events/pending");assertThat(EvidenceUse.comparable(bf,inf,Map.of("b",b,"i",i),r)).isTrue();assertThat(ReportPlan.compile(tree(Map.of("hypotheses",List.of(plan(bf.path("factId").asText())),"checks",List.of())),List.of(b,i),r,false).errors()).isNotEmpty();((com.fasterxml.jackson.databind.node.ObjectNode)i.data()).put("instanceId","other");assertThat(EvidenceUse.comparable(bf,inf,Map.of("b",b,"i",i),r)).isFalse();}
 @Test void explicitPairedComparisonIsRenderedAndUnpairedRejected(){var b=sample("b",r.start().minusSeconds(60).toString(),r.start().minusSeconds(59).toString());var i=sample("i",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());var p=(com.fasterxml.jackson.databind.node.ObjectNode)plan(fact(i,"/events/pending").path("factId").asText());p.putArray("comparisons").add(tree(Map.of("baselineFactId",fact(b,"/events/pending").path("factId").asText(),"incidentFactId",fact(i,"/events/pending").path("factId").asText())));var compiled=ReportPlan.compile(tree(Map.of("hypotheses",List.of(p),"checks",List.of())),List.of(b,i),r,false);assertThat(compiled.errors()).isEmpty();assertThat(compiled.report().path("facts")).hasSize(2);assertThat(ReportPlan.compile(tree(Map.of("hypotheses",List.of(p),"checks",List.of())),List.of(b),r,false).errors()).isNotEmpty();}
 @Test void unsupportedAndRefutedHypothesesNeverPropagateToReport(){for(String state:List.of("PENDING","REFUTED","INSUFFICIENT_EVIDENCE")){var result=Hypotheses.review(assessment(state,JSON.nullNode()),seed(),List.of(),r);assertThat(result.errors()).isEmpty();assertThat(Hypotheses.approved(tree(result.records()))).isEmpty();assertThat(Hypotheses.render(tree(Map.of("hypothesisIds",List.of("H1"),"checks",List.of())),tree(result.records()),List.of(),r,true).errors()).contains("NOT_APPROVED_HYPOTHESIS:H1");assertThat(Hypotheses.render(tree(Map.of("hypothesisIds",List.of(),"checks",List.of())),tree(result.records()),List.of(),r,true).errors()).isEmpty();}}
 @Test void supportedCandidateIsUsableButDoesNotProveCausality(){var e=sample("a",r.start().plusSeconds(20).toString(),r.end().plusSeconds(10).toString());var review=Hypotheses.review(assessment("SUPPORTED",plan(fact(e,"/events/pending").path("factId").asText())),seed(),List.of(e),r);assertThat(review.errors()).isEmpty();var report=Hypotheses.render(tree(Map.of("hypothesisIds",List.of("H1"),"checks",List.of("VERIFY_MECHANISM"))),tree(review.records()),List.of(e),r,false);assertThat(report.errors()).isEmpty();assertThat(report.report().path("candidates")).hasSize(1);assertThat(report.report().at("/candidates/0/confidence").asText()).isEqualTo("UNVERIFIED");}
 @Test void realV85ReferenceCannotSurviveReviewAndCorrectionExplainsUses()throws Exception{var fixture=JSON.readTree(getClass().getResourceAsStream("/model/fault-plan-v85.json"));var request=JSON.treeToValue(fixture.path("input"),Request.class);var es=new ArrayList<Evidence>();for(var e:fixture.path("evidence"))es.add(JSON.treeToValue(e,Evidence.class));var result=Hypotheses.review(assessment("SUPPORTED",fixture.at("/drafts/0/hypotheses/0")),seed(),es,request);assertThat(result.errors()).isNotEmpty();var feedback=encode(Hypotheses.feedback(result.errors(),seed(),es,request));assertThat(feedback).contains("HYPOTHESIS:H1","50a64983-b458-40e7-b7df-606be62d98da","2026-09-12T15:19:48.882739600Z","BACKGROUND","allowedCauseFacts","Withdraw");assertThat(Hypotheses.review(assessment("INSUFFICIENT_EVIDENCE",JSON.nullNode()),seed(),es,request).errors()).isEmpty();}
}
