package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;
import static org.assertj.core.api.Assertions.*;
import java.util.*;import java.time.*;import org.junit.jupiter.api.Test;
class FactReferencesTest {
 final Request r=new Request("tracepilot-business","demo",Instant.parse("2026-09-12T13:00:00Z"),Instant.parse("2026-09-12T13:01:00Z"),"fixture");
 Evidence e(String id,long bytes,String time){return new Evidence(id,"logs","PARTIAL",time,time,Map.of(),tree(Map.of("remainingBytes",bytes,"data",List.of(Map.of("time",time,"status",200)))));}
 com.fasterxml.jackson.databind.node.ObjectNode draft(String id){return (com.fasterxml.jackson.databind.node.ObjectNode)tree(Map.of("summary","待扫描：{{fact:"+id+"}}","facts",List.of(Map.of("factId",id)),"candidates",List.of(),"conflicts",List.of(),"gaps",List.of("覆盖不完整"),"actions",List.of("继续分页")));}
 @Test void decimalBinaryRoundingAndOriginalAreDeterministic(){assertThat(FactReferences.bytes(tree(501757250L))).isEqualTo("501757250 bytes (约 501.76 MB / 约 478.51 MiB；MB=10^6 bytes，MiB=2^20 bytes；小数2位 HALF_UP)");assertThat(FactReferences.bytes(tree(493368988L))).isEqualTo("493368988 bytes (约 493.37 MB / 约 470.51 MiB；MB=10^6 bytes，MiB=2^20 bytes；小数2位 HALF_UP)");assertThat(FactReferences.bytes(tree(1005000))).contains("1.01 MB");}
 @Test void sameFactInProseAndTableUsesSameValueTimeAndSource(){var e=e("a",501757250L,r.start().toString());var c=FactReferences.compile(draft(FactReferences.id("a","/remainingBytes")),List.of(e),r,false);assertThat(c.errors()).isEmpty();assertThat(c.report().path("summary").asText()).contains(c.report().at("/facts/0/text").asText(),e.start(),"501.76 MB");assertThat(c.report().at("/facts/0/value").asLong()).isEqualTo(501757250L);}
 @Test void pagesAndTimesDoNotReplaceEachOther(){var a=e("a",501757250L,r.start().toString());var b=e("b",493368988L,r.end().toString());var d=draft(FactReferences.id("a","/remainingBytes"));d.put("summary","后页：{{fact:"+FactReferences.id("b","/remainingBytes")+"}}");var c=FactReferences.compile(d,List.of(a,b),r,false);assertThat(c.errors()).isEmpty();assertThat(c.report().path("summary").asText()).contains("493.37 MB",r.end().toString());assertThat(c.report().at("/facts/0/text").asText()).contains("501.76 MB",r.start().toString());}
 @Test void unknownMalformedAndContradictoryLiteralAreRejectedNotReplaced(){var e=e("a",10,r.start().toString());var d=draft(FactReferences.id("a","/remainingBytes"));d.put("summary","约493 MB");assertThat(FactReferences.compile(d,List.of(e),r,false).errors()).anyMatch(x->x.startsWith("LITERAL_NUMBER_FORBIDDEN:/summary"));d.put("summary","{{fact:F000000000000000000000000}}");assertThat(FactReferences.compile(d,List.of(e),r,false).errors()).anyMatch(x->x.startsWith("UNKNOWN_FACT_ID:/summary"));d.put("summary","{{fact:"+FactReferences.id("a","/remainingBytes")+"}} MiB");assertThat(FactReferences.compile(d,List.of(e),r,false).errors()).anyMatch(x->x.startsWith("LITERAL_UNIT_FORBIDDEN"));d.put("summary","{{fact:missing}}");assertThat(FactReferences.compile(d,List.of(e),r,false).errors()).contains("MALFORMED_FACT_REFERENCE:/summary");}
 @Test void allCandidateAndAdviceTextIsChecked(){var e=e("a",10,r.start().toString());var d=draft(FactReferences.id("a","/remainingBytes"));d.putArray("candidates").add(tree(Map.of("cause","积压八个","mechanism","wait 8 seconds","support","3次","contradictions","零次","toVerify",List.of("等待20秒"))));d.putArray("actions").add("等待1分钟");var errors=FactReferences.compile(d,List.of(e),r,false).errors();for(var f:List.of("cause","mechanism","support","contradictions","toVerify/0"))assertThat(errors).anyMatch(x->x.contains("/candidates/0/"+f));assertThat(errors).anyMatch(x->x.contains("/actions/0"));}
 @Test void versionsAndErrorCodesArePreservedByReferencesNotDigitReplacement(){var e=new Evidence("u","overview","UNAVAILABLE",r.start().toString(),r.end().toString(),Map.of(),tree(Map.of("httpStatus",503,"deploymentVersion","build-v8.3")));var a=tree(Map.of("type","insufficient","summary","来源：{{fact:"+FactReferences.id("u","/httpStatus")+"}}；版本：{{fact:"+FactReferences.id("u","/deploymentVersion")+"}}","gaps",List.of("缺少证据"),"actions",List.of("恢复来源")));var c=FactReferences.compile(a,List.of(e),r,true);assertThat(c.errors()).isEmpty();assertThat(c.report().path("summary").asText()).contains("503","build-v8.3");assertThat(c.report().path("type").asText()).isEqualTo("insufficient");}
 @Test void originalRealMismatchCannotPassNewContract()throws Exception{var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-facts-v83.json"));var es=new ArrayList<Evidence>();for(var e:f.path("evidence"))es.add(JSON.treeToValue(e,Evidence.class));var c=FactReferences.compile(f.path("report"),es,JSON.treeToValue(f.path("input"),Request.class),false);assertThat(c.errors()).contains("FACT_ID_ONLY:/facts/2");assertThat(c.errors()).anyMatch(x->x.startsWith("LITERAL_NUMBER_FORBIDDEN:/summary"));assertThat(f.at("/report/facts/2/value").asLong()).isEqualTo(501757250L);}
 @Test void realSyntaxMaskIsCompleteButOriginalUnknownKeyIdentityIsMissing()throws Exception{var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-syntax-v83.json"));var c=f.path("capture");assertThat(c.at("/parserText/complete").asBoolean()).isTrue();String body=c.at("/parserText/text").asText();assertThat(JSON.readTree(body).isObject()).isTrue();var rejected=SpringAiGateway.parseAnswer(body,"end_turn");assertThat(rejected.path("parseCategory").asText()).isEqualTo("DUPLICATE_JSON_FIELD");assertThat(rejected.path("characterOffset").asLong()).isEqualTo(c.path("offset").asLong());}
 @Test void duplicateKeysRemainRejectedAndCorrectedBodyIsSeparatelyValid(){var rejected=SpringAiGateway.parseAnswer("{\"type\":\"report\",\"contradictions\":\"a\",\"contradictions\":\"b\"}","end_turn");assertThat(rejected.path("parseCategory").asText()).isEqualTo("DUPLICATE_JSON_FIELD");assertThat(rejected.at("/syntaxCapture/parserText/text").asText()).contains("contradictions");assertThat(SpringAiGateway.parseAnswer("{\"type\":\"report\",\"contradictions\":\"a\"}","end_turn").path("type").asText()).isEqualTo("report");}
}
