package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;
import static org.assertj.core.api.Assertions.*;
import java.util.*;import java.time.*;import org.junit.jupiter.api.Test;
class ReportPlanTest {
 final Request r=new Request("tracepilot-business","demo",Instant.parse("2026-09-12T13:00:00Z"),Instant.parse("2026-09-12T13:01:00Z"),"fixture");
 Evidence e(String id,int value,String time){return new Evidence(id,"metrics","AVAILABLE",time,time,Map.of("service",r.service()),tree(Map.of("data",List.of(Map.of("time",time,"deploymentVersion",MetricFacts.BUSINESS_VERSION,"events",Map.of("pending",value))))));}
 com.fasterxml.jackson.databind.node.ObjectNode plan(String... refs){return (com.fasterxml.jackson.databind.node.ObjectNode)tree(Map.of("hypotheses",refs.length==0?List.of():List.of(Map.of("relation","MAY_EXPLAIN","premiseFactIds",List.of(refs),"outcomeFactIds",List.of(),"contradictionFactIds",List.of(),"checks",List.of("VERIFY_MECHANISM"))),"checks",List.of("CHECK_ALTERNATIVES")));}
 String id(String e){return FactReferences.id(e,"/data/0/events/pending");}
 @Test void oneCandidateUsesOnlyRegisteredValuesAndProgramInference(){var es=List.of(e("a",8,r.start().toString()));var c=ReportPlan.compile(plan(id("a")),es,r,false);assertThat(c.errors()).isEmpty();assertThat(EvidenceRegistry.validate(c.report(),es,r)).isEmpty();assertThat(c.report().at("/candidates/0/inference").asBoolean()).isTrue();assertThat(c.report().at("/facts/0/value").asInt()).isEqualTo(8);assertThat(c.report().at("/candidates/0/support").asText()).isEqualTo(c.report().at("/facts/0/text").asText());}
 @Test void pagesRemainBoundToExactIdAndValue(){var c=ReportPlan.compile(plan(id("a"),id("b")),List.of(e("a",8,r.start().toString()),e("b",3,r.end().toString())),r,false);assertThat(c.errors()).isEmpty();assertThat(c.report().at("/facts/0/value").asInt()).isEqualTo(8);assertThat(c.report().at("/facts/1/value").asInt()).isEqualTo(3);assertThat(c.report().at("/facts/0/text").asText()).contains(r.start().toString(),"证据=a");assertThat(c.report().at("/facts/1/text").asText()).contains(r.end().toString(),"证据=b");}
 @Test void ordinaryLanguageAndNumbersArePreservedOnlyAsUnreviewedNotes(){var p=plan(id("a"));p.put("reviewNote","一段时间，493 MB，HTTP 503，v8.4");var c=ReportPlan.compile(p,List.of(e("a",8,r.start().toString())),r,false);assertThat(c.errors()).isEmpty();assertThat(c.report().at("/reviewNotes/0/text").asText()).isEqualTo(p.path("reviewNote").asText());for(var field:List.of("summary","candidates","facts","gaps","actions"))assertThat(c.report().path(field).toString()).doesNotContain("493 MB","一段时间","v8.4");}
 @Test void mandatoryFieldsNotGuessedAndFreeMetricProseRejectedStructurally(){var p=plan(id("a"));((com.fasterxml.jackson.databind.node.ObjectNode)p.at("/hypotheses/0")).remove("relation");assertThat(ReportPlan.compile(p,List.of(e("a",8,r.start().toString())),r,false).errors()).contains("MISSING_FIELD:/hypotheses/0/relation");p=plan();p.put("summary","493 MB");assertThat(ReportPlan.compile(p,List.of(),r,true).errors()).contains("UNEXPECTED_FIELD:/summary");}
 @Test void unknownForeignAndWrongWindowReferencesAreDenied(){assertThat(ReportPlan.compile(plan("foreign"),List.of(),r,false).errors()).anyMatch(x->x.startsWith("UNKNOWN_OR_UNAUTHORIZED_FACT"));assertThat(ReportPlan.compile(plan(id("a")),List.of(e("a",8,"2026-09-12T12:00:00Z")),r,false).errors()).anyMatch(x->x.startsWith("NOT_INCIDENT_OBSERVATION"));var foreign=new Evidence("a","metrics","AVAILABLE",r.start().toString(),r.end().toString(),Map.of("service","foreign"),e("a",8,r.start().toString()).data());assertThat(ReportPlan.compile(plan(id("a")),List.of(foreign),r,false).errors()).anyMatch(x->x.startsWith("NOT_INCIDENT_OBSERVATION"));}
 @Test void emptyAndUnavailableHaveLegalNoCauseReports(){var es=List.of(new Evidence("u","logs","UNAVAILABLE",r.start().toString(),r.end().toString(),Map.of(),tree(Map.of("httpStatus",503))));var c=ReportPlan.compile(plan(),es,r,true);assertThat(c.errors()).isEmpty();assertThat(c.report().path("candidates")).isEmpty();assertThat(c.report().path("resultType").asText()).isEqualTo("INSUFFICIENT_EVIDENCE_SOURCE_FAILURE");assertThat(EvidenceRegistry.validate(c.report(),es,r)).isEmpty();}
 @Test void realRejectedDraftsRequireExplicitNewPlanNotSilentMigration()throws Exception{var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-plan-v84.json"));for(var draft:f.path("drafts")){assertThat(ReportPlan.compile(draft,List.of(),r,false).errors()).contains("MISSING_FIELD:/hypotheses","MISSING_FIELD:/checks");assertThat(draft.at("/candidates/0").has("inference")).isFalse();}assertThat(f.path("drafts").toString()).contains("一段时间","493");}
 @Test void schemaAndPromptUseSamePlanDefinitionAndLegacyReportRemainsReadable()throws Exception{assertThat(Workflow.prompt("REVIEW")).contains(encode(ReviewContract.schema()));var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-facts-v83.json"));var saved=f.path("report");assertThat(parse(encode(saved))).isEqualTo(saved);assertThat(saved.path("facts").isArray()).isTrue();}
 @Test void validSnapshotRemainsUsableButScanMetadataCannotProveIncident(){var live=e("a",8,r.start().toString());var stored=new Evidence(live.id(),live.source(),"STALE",live.start(),live.end(),live.locator(),live.data());assertThat(ReportPlan.compile(plan(id("a")),List.of(stored),r,false).errors()).isEmpty();var scan=new Evidence("s","logs","PARTIAL",r.start().toString(),r.end().toString(),Map.of(),tree(Map.of("remainingBytes",501757250,"data",List.of(Map.of("status",200)))));assertThat(ReportPlan.compile(plan(FactReferences.id("s","/remainingBytes")),List.of(scan),r,false).errors()).anyMatch(x->x.startsWith("NOT_INCIDENT_OBSERVATION"));}
 @Test void eachCandidateValidatedAndWithdrawalIsExplicit(){var p=plan(id("a"));var bad=plan("fake").at("/hypotheses/0");((com.fasterxml.jackson.databind.node.ArrayNode)p.path("hypotheses")).add(bad);var es=List.of(e("a",8,r.start().toString()));assertThat(ReportPlan.compile(p,es,r,false).errors()).anyMatch(x->x.contains("/hypotheses/1/premiseFactIds"));assertThat(p.path("hypotheses")).hasSize(2);((com.fasterxml.jackson.databind.node.ArrayNode)p.path("hypotheses")).remove(1);assertThat(ReportPlan.compile(p,es,r,false).errors()).isEmpty();}
 @Test void overviewAuthorityDependsOnActualVersionAndTimestamp(){var data=tree(Map.of("time",r.start().toString(),"deploymentVersion",MetricFacts.BUSINESS_VERSION,"events",Map.of("pending",8)));var o=new Evidence("o","overview","AVAILABLE",r.start().toString(),r.start().toString(),Map.of(),data);assertThat(ReportPlan.compile(plan(FactReferences.id("o","/events/pending")),List.of(o),r,false).errors()).isEmpty();((com.fasterxml.jackson.databind.node.ObjectNode)data).put("deploymentVersion","unknown");assertThat(ReportPlan.compile(plan(FactReferences.id("o","/events/pending")),List.of(o),r,false).errors()).anyMatch(x->x.startsWith("NOT_INCIDENT_OBSERVATION"));}
 @Test void realV85DraftsReproduceWrongWindowRejectionWithoutModelCalls()throws Exception{var f=JSON.readTree(getClass().getResourceAsStream("/model/fault-plan-v85.json"));var request=JSON.treeToValue(f.path("input"),Request.class);var es=new ArrayList<Evidence>();for(var e:f.path("evidence"))es.add(JSON.treeToValue(e,Evidence.class));for(var draft:f.path("drafts")){var c=ReportPlan.compile(draft,es,request,false);assertThat(c.errors()).hasSize(7).allMatch(x->x.startsWith("NOT_INCIDENT_OBSERVATION:"));assertThat(c.report().isEmpty()).isTrue();}assertThat(es.getFirst().start()).isGreaterThan(request.end().toString());}
}
