package com.tracepilot.diagnosis;
import static com.tracepilot.diagnosis.Domain.*;import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import java.util.*;import java.time.*;import org.junit.jupiter.api.Test;
class SingleReferenceTest {
 JsonNode fixture()throws Exception{return parse(new String(getClass().getResourceAsStream("/model/review-v883.json").readAllBytes(),java.nio.charset.StandardCharsets.UTF_8));}
 Request request()throws Exception{return JSON.treeToValue(fixture().path("request"),Request.class);}
 List<Evidence> evidence()throws Exception{var out=new ArrayList<Evidence>();for(var e:fixture().path("evidence"))out.add(JSON.treeToValue(e,Evidence.class));return out;}
 static void wire(JsonNode review){for(var h:review.path("assessments"))if(h.path("plan").isObject())((ObjectNode)h.path("plan")).putNull("mechanism");var root=(ObjectNode)review;root.remove(List.of("conflicts","gaps"));for(var a:review.path("assessments")){var o=(ObjectNode)a;o.remove(List.of("supportFactIds","contradictionFactIds","gaps"));o.set("issues",tree(List.of("VERIFY_MECHANISM","CHECK_ALTERNATIVES")));if(o.path("plan").isObject())((ObjectNode)o.path("plan")).remove(List.of("timelineNodeIds","reviewNote","checks"));}}
 @Test void actualRedundantFieldsRejectedButSingleReferencesDeriveNodes()throws Exception{var f=fixture();var original=f.path("rounds").get(3).path("action");var prior=tree(Hypotheses.seed(f.path("rounds").get(0).path("action").path("candidates")));var rejected=ReviewContract.review(original,prior,evidence(),request());assertThat(rejected.errors().toString()).contains("UNEXPECTED_FIELD");var corrected=original.deepCopy();wire(corrected);var accepted=ReviewContract.review(corrected,prior,evidence(),request());assertThat(accepted.errors()).isEmpty();var rendered=ReviewContract.render(tree(Map.of("hypothesisIds",List.of("H1"),"checks",List.of())),tree(accepted.records()),evidence(),request(),false);assertThat(rendered.errors()).isEmpty();assertThat(rendered.report().path("schemaVersion").asText()).isEqualTo(ReviewContract.VERSION);assertThat(rendered.report().path("modelPlan").toString()).doesNotContain("timelineNodeIds","reviewNote");assertThat(rendered.report().path("timeComparisons")).isNotEmpty();assertThat(rendered.report().path("unresolvedQuestions").toString()).doesNotContain("failed", "50s");}
 @Test void extraRealNodeCanBeChosenByItsRelevantFactWithoutAnEqualitySet()throws Exception{var f=fixture();var a=f.path("rounds").get(3).path("action").deepCopy();wire(a);var plan=(ObjectNode)a.path("assessments").get(0).path("plan");String failed=FactReferences.id(evidence().get(1).id(),"/data/6/status");plan.set("premiseFactIds",tree(List.of(failed)));var prior=tree(Hypotheses.seed(f.path("rounds").get(0).path("action").path("candidates")));assertThat(ReviewContract.review(a,prior,evidence(),request()).errors()).isEmpty();plan.set("premiseFactIds",tree(List.of("Funknown")));assertThat(ReviewContract.review(a,prior,evidence(),request()).errors().toString()).contains("UNKNOWN_OR_UNAUTHORIZED_FACT");}
 @Test void freeGapProseAndDuplicateSetsAreNotAccepted()throws Exception{var f=fixture();var a=f.path("rounds").get(3).path("action").deepCopy();wire(a);((ObjectNode)a.path("assessments").get(0)).set("issues",tree(List.of("failed before first empty query")));assertThat(ReviewContract.review(a,tree(List.of()),evidence(),request()).errors().toString()).contains("INVALID_ENUM");}
 @Test void deterministicComparisonKeepsStartAndFailureSeparate()throws Exception{var c=EventTimeline.build(evidence(),request());var start=c.nodes().stream().filter(n->n.path("eventTime").asText().equals("2026-09-15T07:34:59.693Z")).findFirst().orElseThrow();var query=c.nodes().stream().filter(n->n.path("eventTime").asText().equals("2026-09-15T07:35:01.729Z")).findFirst().orElseThrow();var failure=c.nodes().stream().filter(n->n.path("action").asText().equals("notification_attempt_error")).findFirst().orElseThrow();assertThat(TimeComparisons.compare(start,query).get("order")).isEqualTo("LEFT_OBSERVED_BEFORE_RIGHT");assertThat(TimeComparisons.compare(failure,query).get("order")).isEqualTo("LEFT_OBSERVED_AFTER_RIGHT");assertThat(TimeComparisons.compare(failure,query).get("left").toString()).contains("消费处理异常");assertThat(TimeComparisons.compare(start,query).get("left").toString()).contains("开始调用");assertThat(TimeComparisons.compare(start,start).get("order")).isEqualTo("UNRESOLVED_WITHIN_PRECISION");}
 @Test void unknownClockAndCommitPrecisionRemainExplicit()throws Exception{var c=EventTimeline.build(evidence(),request());var n=c.nodes().get(0);var other=(ObjectNode)n.deepCopy();other.put("instanceId","other");assertThat(TimeComparisons.compare(n,other).get("order")).isEqualTo("UNKNOWN");var commit=c.nodes().stream().filter(x->x.path("action").asText().equals("notification_write_committed")).findFirst().orElseThrow();assertThat(TimeComparisons.compare(n,commit).get("right").toString()).contains("非精确提交时刻");}
 @Test void sourceGapCannotBeUsedAsCauseAndEmptyReportStillWorks()throws Exception{var report=ReviewContract.render(tree(Map.of("hypothesisIds",List.of(),"checks",List.of())),tree(List.of()),List.of(),request(),true);assertThat(report.errors()).isEmpty();assertThat(report.report().path("candidates")).isEmpty();assertThat(report.report().path("timeComparisons")).isEmpty();assertThat(parse(encode(fixture().path("rounds")))).isEqualTo(fixture().path("rounds"));}
}
